fix: add missing percentage sign in storage usage log message
Double %% is required to escape the percentage sign in the string format.

Fixes this error:
  ```
    File "/usr/lib64/python3.13/logging/__init__.py", line 400, in getMessage
      msg = msg % self.args
            ~~~~^~~~~~~~~~~
  TypeError: not enough arguments for format string
  ...
      logging.info("Storage is %d % full. Cleaning up cached rpmdb.", usage)
  Message: 'Storage is %d % full. Cleaning up cached rpmdb.'
  Arguments: (98,)
  ```